kind: pipeline
name: grpc-test-server

steps:
  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB.USER
      password:
        from_secret: DOCKERHUB.PASSWORD
      repo: folkertest/grpc-test-server
      tags:
        - latest
        - "0.2.${DRONE_BUILD_NUMBER}"
    when:
      branch:
        - main
        - release
      event: push
