// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProto.proto

package test;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_TestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_TestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_TestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_TestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017TestProto.proto\022\004test\"2\n\013TestRequest\022\021" +
      "\n\tfirstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\" \n\014T" +
      "estResponse\022\020\n\010greeting\030\001 \001(\t2p\n\013TestSer" +
      "vice\022.\n\005hello\022\021.test.TestRequest\032\022.test." +
      "TestResponse\0221\n\006hellos\022\021.test.TestReques" +
      "t\032\022.test.TestResponse0\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_TestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_TestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_TestRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_test_TestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_TestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_TestResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
