// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProto.proto

package test;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
